---
- hosts: localhost
  gather_facts: True
  tasks:
  - name: Write test-file.txt in /tmp folder
    copy:
      content: "file content for instance {{ ansible_hostname }}"
      dest: /tmp/test-file-{{ ansible_hostname }}.txt
